# kubectl -n osg-gil create secret generic certs-400 --from-file=$HOME/private/certs/xrd-ipv6-certs/certs-400/hostcert.pem --from-file=$HOME/private/certs/xrd-ipv6-certs/certs-400/hostcert.key.pem --from-file=$HOME/private/certs/xrd-ipv6-certs/certs-400/macaroon-secret
# kubectl -n osg-gil create secret generic certs-500 --from-file=$HOME/private/certs/xrd-ipv6-certs/certs-500/hostcert.pem --from-file=$HOME/private/certs/xrd-ipv6-certs/certs-500/hostcert.key.pem --from-file=$HOME/private/certs/xrd-ipv6-certs/certs-500/macaroon-secret
# kubectl -n osg-gil create secret generic certs-600 --from-file=$HOME/private/certs/xrd-ipv6-certs/certs-600/hostcert.pem --from-file=$HOME/private/certs/xrd-ipv6-certs/certs-600/hostcert.key.pem --from-file=$HOME/private/certs/xrd-ipv6-certs/certs-600/macaroon-secret
# kubectl -n osg-gil create secret generic certs-700 --from-file=$HOME/private/certs/xrd-ipv6-certs/certs-700/hostcert.pem --from-file=$HOME/private/certs/xrd-ipv6-certs/certs-700/hostcert.key.pem --from-file=$HOME/private/certs/xrd-ipv6-certs/certs-700/macaroon-secret
# kubectl -n osg-gil create secret generic certs-redi --from-file=$HOME/private/certs/xrd-ipv6-certs/certs-redi/hostcert.pem --from-file=$HOME/private/certs/xrd-ipv6-certs/certs-redi/hostcert.key.pem --from-file=$HOME/private/certs/xrd-ipv6-certs/certs-redi/macaroon-secret
# kubectl -n osg-gil create secret generic certs-cern --from-file=$HOME/private/certs/xrd-ipv6-certs/certs-cern/hostcert.pem --from-file=$HOME/private/certs/xrd-ipv6-certs/certs-cern/hostcert.key.pem --from-file=$HOME/private/certs/xrd-ipv6-certs/certs-cern/macaroon-secret
kubectl -n osg-gil create secret generic certs-mghpcc-3 --from-file=$HOME/private/certs/xrd-ipv6-certs/certs-mghpcc-3/hostcert.pem --from-file=$HOME/private/certs/xrd-ipv6-certs/certs-mghpcc-3/hostcert.key.pem --from-file=$HOME/private/certs/xrd-ipv6-certs/certs-mghpcc-3/macaroon-secret
kubectl -n osg-gil create secret generic certs-mghpcc-4 --from-file=$HOME/private/certs/xrd-ipv6-certs/certs-mghpcc-4/hostcert.pem --from-file=$HOME/private/certs/xrd-ipv6-certs/certs-mghpcc-4/hostcert.key.pem --from-file=$HOME/private/certs/xrd-ipv6-certs/certs-mghpcc-4/macaroon-secret
kubectl -n osg-gil create secret generic certs-mghpcc-5 --from-file=$HOME/private/certs/xrd-ipv6-certs/certs-mghpcc-5/hostcert.pem --from-file=$HOME/private/certs/xrd-ipv6-certs/certs-mghpcc-5/hostcert.key.pem --from-file=$HOME/private/certs/xrd-ipv6-certs/certs-mghpcc-5/macaroon-secret
kubectl -n osg-gil create secret generic certs-mghpcc-6 --from-file=$HOME/private/certs/xrd-ipv6-certs/certs-mghpcc-6/hostcert.pem --from-file=$HOME/private/certs/xrd-ipv6-certs/certs-mghpcc-6/hostcert.key.pem --from-file=$HOME/private/certs/xrd-ipv6-certs/certs-mghpcc-6/macaroon-secret
kubectl -n osg-gil create secret generic certs-mghpcc-redi --from-file=$HOME/private/certs/xrd-ipv6-certs/certs-mghpcc-redi/hostcert.pem --from-file=$HOME/private/certs/xrd-ipv6-certs/certs-mghpcc-redi/hostcert.key.pem --from-file=$HOME/private/certs/xrd-ipv6-certs/certs-mghpcc-redi/macaroon-secret
