delete:
	- kubectl -n osg-gil delete -k ./deployments/rucio-sense-redi-111-800
	- kubectl -n osg-gil delete -k ./deployments/rucio-sense-redi-112-800
	- kubectl -n osg-gil delete -k ./deployments/rucio-sense-redi-113-800
create:
	- kubectl -n osg-gil apply -k ./deployments/rucio-sense-redi-111-800
	- kubectl -n osg-gil apply -k ./deployments/rucio-sense-redi-112-800
	- kubectl -n osg-gil apply -k ./deployments/rucio-sense-redi-113-800
