delete:
	- kubectl -n osg-gil delete -k ./deployments/rucio-sense-server-k8s-gen4-02-400
	- kubectl -n osg-gil delete -k ./deployments/rucio-sense-server-k8s-gen4-02-500
	- kubectl -n osg-gil delete -k ./deployments/rucio-sense-server-k8s-gen4-02-600
	- kubectl -n osg-gil delete -k ./deployments/rucio-sense-server-k8s-gen4-02-700
	- kubectl -n osg-gil delete -k ./deployments/rucio-sense-server-k8s-gen4-01-400
	- kubectl -n osg-gil delete -k ./deployments/rucio-sense-server-k8s-gen4-01-500
	- kubectl -n osg-gil delete -k ./deployments/rucio-sense-server-k8s-gen4-01-600
	- kubectl -n osg-gil delete -k ./deployments/rucio-sense-server-k8s-gen4-01-700
create:
	- kubectl -n osg-gil apply -k ./deployments/rucio-sense-server-k8s-gen4-02-400
	- kubectl -n osg-gil apply -k ./deployments/rucio-sense-server-k8s-gen4-02-500
	- kubectl -n osg-gil apply -k ./deployments/rucio-sense-server-k8s-gen4-02-600
	- kubectl -n osg-gil apply -k ./deployments/rucio-sense-server-k8s-gen4-02-700
	- kubectl -n osg-gil apply -k ./deployments/rucio-sense-server-k8s-gen4-01-400
	- kubectl -n osg-gil apply -k ./deployments/rucio-sense-server-k8s-gen4-01-500
	- kubectl -n osg-gil apply -k ./deployments/rucio-sense-server-k8s-gen4-01-600
	- kubectl -n osg-gil apply -k ./deployments/rucio-sense-server-k8s-gen4-01-700
