delete:
	- kubectl delete -k ./deployments/rucio-sense-server-k8s-gen4-01-111-1094
	- kubectl delete -k ./deployments/rucio-sense-server-k8s-gen4-02-112-1094
create:
	- kubectl apply -k ./deployments/rucio-sense-server-k8s-gen4-01-111-1094
	- kubectl apply -k ./deployments/rucio-sense-server-k8s-gen4-02-112-1094
