delete:
	- kubectl -n osg-gil delete -k ./deployments/rucio-sense-server-k8s-gen4-02-111-1094
	- kubectl -n osg-gil delete -k ./deployments/rucio-sense-server-k8s-gen4-02-1-1-1094
	- kubectl -n osg-gil delete -k ./deployments/rucio-sense-server-k8s-gen4-02-1-4-1094
create:
	- kubectl -n osg-gil apply -k ./deployments/rucio-sense-server-k8s-gen4-02-111-1094
	- kubectl -n osg-gil apply -k ./deployments/rucio-sense-server-k8s-gen4-02-1-1-1094
	- kubectl -n osg-gil apply -k ./deployments/rucio-sense-server-k8s-gen4-02-1-4-1094
