# Default values for rucio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: aaarora/rucio-sense-xrootd
  pullPolicy: Always
  tag: latest

tolerations:
  - key: "nautilus.io/sense"
    operator: "Exists"
    effect: "NoSchedule"

storagePath: # storage mounted at /rucio
  emptyDir:
    medium: Memory
    sizeLimit: 128Gi

rediResources:
  limits:
    cpu: 128
    memory: 256Gi
  requests:
    cpu: 6
    memory: 16Gi

originResources:
  limits:
    cpu: 128
    memory: 256Gi
  requests:
    cpu: 8
    memory: 140Gi

clusters:
  cluster-0:
    redirector:
      name: redirector-0
      multus: "mghpcc-0"
      iprange: "2001:48e8:6402:0::2/60"
      mac: "4a:1c:51:71:fc:18"
      gateway: "2001:48e8:6402:0::1"
      ip: "2001:48e8:6402:0::2"
      node: "nrp-sense01.rnd.net2.mghpcc.org "
      certs: "certs-mghpcc-redi"
    origins:
      - name: origin-0-3
        multus: "mghpcc-0"
        iprange: "2001:48e8:6402:0::3/60"
        mac: "ae:1e:e0:d5:4a:be"
        gateway: "2001:48e8:6402:0::1"
        ip: "2001:48e8:6402:0::3"
        node: "nrp-sense01.rnd.net2.mghpcc.org "
        certs: "certs-mghpcc-3"
      - name: origin-0-4
        multus: "mghpcc-0"
        iprange: "2001:48e8:6402:0::4/60"
        mac: "72:eb:dc:7a:2a:92"
        gateway: "2001:48e8:6402:0::1"
        ip: "2001:48e8:6402:0::4"
        node: "nrp-sense01.rnd.net2.mghpcc.org "
        certs: "certs-mghpcc-4"
      - name: origin-0-5
        multus: "mghpcc-0"
        iprange: "2001:48e8:6402:0::5/60"
        mac: "16:81:4b:aa:a4:c3"
        gateway: "2001:48e8:6402:0::1"
        ip: "2001:48e8:6402:0::5"
        node: "nrp-sense01.rnd.net2.mghpcc.org "
        certs: "certs-mghpcc-5"
      - name: origin-0-6
        multus: "mghpcc-0"
        iprange: "2001:48e8:6402:0::6/60"
        mac: "4a:b2:27:43:4a:70"
        gateway: "2001:48e8:6402:0::1"
        ip: "2001:48e8:6402:0::6"
        node: "nrp-sense01.rnd.net2.mghpcc.org "
        certs: "certs-mghpcc-6"

  cluster-1:
    redirector:
      name: redirector-1
      multus: "mghpcc-1"
      iprange: "2001:48e8:6402:1::2/60"
      mac: "3e:d2:f0:23:9b:6e"
      gateway: "2001:48e8:6402:0::1"
      ip: "2001:48e8:6402:1::2"
      node: "nrp-sense01.rnd.net2.mghpcc.org "
      certs: "certs-mghpcc-redi"
    origins:
      - name: origin-1-3
        multus: "mghpcc-1"
        iprange: "2001:48e8:6402:1::3/60"
        mac: "7a:ff:0e:fe:7f:1b"
        gateway: "2001:48e8:6402:0::1"
        ip: "2001:48e8:6402:1::3"
        node: "nrp-sense01.rnd.net2.mghpcc.org "
        certs: "certs-mghpcc-3"
      - name: origin-1-4
        multus: "mghpcc-1"
        iprange: "2001:48e8:6402:1::4/60"
        mac: "2e:e0:b0:a3:ab:b5"
        gateway: "2001:48e8:6402:0::1"
        ip: "2001:48e8:6402:1::4"
        node: "nrp-sense01.rnd.net2.mghpcc.org "
        certs: "certs-mghpcc-4"
      - name: origin-1-5
        multus: "mghpcc-1"
        iprange: "2001:48e8:6402:1::5/60"
        mac: "d6:12:52:9d:a4:11"
        gateway: "2001:48e8:6402:0::1"
        ip: "2001:48e8:6402:1::5"
        node: "nrp-sense01.rnd.net2.mghpcc.org "
        certs: "certs-mghpcc-5"
      - name: origin-1-6
        multus: "mghpcc-1"
        iprange: "2001:48e8:6402:1::6/60"
        mac: "3e:6e:02:b3:8b:fc"
        gateway: "2001:48e8:6402:0::1"
        ip: "2001:48e8:6402:1::6"
        node: "nrp-sense01.rnd.net2.mghpcc.org "
        certs: "certs-mghpcc-6"

  cluster-2:
    redirector:
      name: redirector-2
      multus: "mghpcc-2"
      iprange: "2001:48e8:6402:2::2/60"
      mac: "56:06:26:bb:3b:df"
      gateway: "2001:48e8:6402:0::1"
      ip: "2001:48e8:6402:2::2"
      node: "nrp-sense01.rnd.net2.mghpcc.org "
      certs: "certs-mghpcc-redi"
    origins:
      - name: origin-2-3
        multus: "mghpcc-2"
        iprange: "2001:48e8:6402:2::3/60"
        mac: "3a:bf:99:05:12:3f"
        gateway: "2001:48e8:6402:0::1"
        ip: "2001:48e8:6402:2::3"
        node: "nrp-sense01.rnd.net2.mghpcc.org "
        certs: "certs-mghpcc-3"
      - name: origin-2-4
        multus: "mghpcc-2"
        iprange: "2001:48e8:6402:2::4/60"
        mac: "46:59:44:bf:a8:39"
        gateway: "2001:48e8:6402:0::1"
        ip: "2001:48e8:6402:2::4"
        node: "nrp-sense01.rnd.net2.mghpcc.org "
        certs: "certs-mghpcc-4"
      - name: origin-2-5
        multus: "mghpcc-2"
        iprange: "2001:48e8:6402:2::5/60"
        mac: "ea:34:ff:32:c3:12"
        gateway: "2001:48e8:6402:0::1"
        ip: "2001:48e8:6402:2::5"
        node: "nrp-sense01.rnd.net2.mghpcc.org "
        certs: "certs-mghpcc-5"
      - name: origin-2-6
        multus: "mghpcc-2"
        iprange: "2001:48e8:6402:2::6/60"
        mac: "a2:c4:37:a0:d3:ff"
        gateway: "2001:48e8:6402:0::1"
        ip: "2001:48e8:6402:2::6"
        node: "nrp-sense01.rnd.net2.mghpcc.org "
        certs: "certs-mghpcc-6"