# Default values for rucio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: aaarora/rucio-sense-xrootd
  pullPolicy: Always
  tag: latest

tolerations:
  - key: "nautilus.io/sense"
    operator: "Exists"
    effect: "NoSchedule"

storagePath: # storage mounted at /rucio
  emptyDir:
    medium: Memory
    sizeLimit: 128Gi

rediResources:
  limits:
    cpu: 128
    memory: 256Gi
  requests:
    cpu: 8
    memory: 16Gi

originResources:
  limits:
    cpu: 128
    memory: 256Gi
  requests:
    cpu: 8
    memory: 140Gi

clusters:
  cluster-0:
    redirector:
      name: redirector-0
      multus: "mghpcc-0"
      iprange: "2001:48e8:6402:0::2/64"
      gateway: "2001:48e8:6402:0::1"
      ip: "2001:48e8:6402:0::2"
      node: "nrp-sense01.rnd.net2.mghpcc.org "
      certs: "certs-mghpcc-0"
    origins:
      - name: origin-0-3
        multus: "mghpcc-0"
        iprange: "2001:48e8:6402:0::3/64"
        gateway: "2001:48e8:6402:0::1"
        ip: "2001:48e8:6402:0::3"
        node: "nrp-sense01.rnd.net2.mghpcc.org "
        certs: "certs-mghpcc-0"
      - name: origin-0-4
        multus: "mghpcc-0"
        iprange: "2001:48e8:6402:0::4/64"
        gateway: "2001:48e8:6402:0::1"
        ip: "2001:48e8:6402:0::4"
        node: "nrp-sense01.rnd.net2.mghpcc.org "
        certs: "certs-mghpcc-0"
      - name: origin-0-5
        multus: "mghpcc-0"
        iprange: "2001:48e8:6402:0::5/64"
        gateway: "2001:48e8:6402:0::1"
        ip: "2001:48e8:6402:0::5"
        node: "nrp-sense01.rnd.net2.mghpcc.org "
        certs: "certs-mghpcc-0"
      - name: origin-0-6
        multus: "mghpcc-0"
        iprange: "2001:48e8:6402:0::6/64"
        gateway: "2001:48e8:6402:0::1"
        ip: "2001:48e8:6402:0::6"
        node: "nrp-sense01.rnd.net2.mghpcc.org "
        certs: "certs-mghpcc-0"

  cluster-1:
    redirector:
      name: redirector-1
      multus: "mghpcc-1"
      iprange: "2001:48e8:6402:1::2/64"
      gateway: "2001:48e8:6402:1::0"
      ip: "2001:48e8:6402:1::2"
      node: "nrp-sense01.rnd.net2.mghpcc.org "
      certs: "certs-mghpcc-1"
    origins:
      - name: origin-1-3
        multus: "mghpcc-1"
        iprange: "2001:48e8:6402:1::3/64"
        gateway: "2001:48e8:6402:1::0"
        ip: "2001:48e8:6402:1::3"
        node: "nrp-sense01.rnd.net2.mghpcc.org "
        certs: "certs-mghpcc-1"
      - name: origin-1-4
        multus: "mghpcc-1"
        iprange: "2001:48e8:6402:1::4/64"
        gateway: "2001:48e8:6402:1::0"
        ip: "2001:48e8:6402:1::4"
        node: "nrp-sense01.rnd.net2.mghpcc.org "
        certs: "certs-mghpcc-1"
      - name: origin-1-5
        multus: "mghpcc-1"
        iprange: "2001:48e8:6402:1::5/64"
        gateway: "2001:48e8:6402:1::0"
        ip: "2001:48e8:6402:1::5"
        node: "nrp-sense01.rnd.net2.mghpcc.org "
        certs: "certs-mghpcc-1"
      - name: origin-1-6
        multus: "mghpcc-1"
        iprange: "2001:48e8:6402:1::6/64"
        gateway: "2001:48e8:6402:1::0"
        ip: "2001:48e8:6402:1::6"
        node: "nrp-sense01.rnd.net2.mghpcc.org "
        certs: "certs-mghpcc-1"

  cluster-2:
    redirector:
      name: redirector-2
      multus: "mghpcc-2"
      iprange: "2001:48e8:6402:2::2/64"
      gateway: "2001:48e8:6402:2::0"
      ip: "2001:48e8:6402:2::2"
      node: "nrp-sense01.rnd.net2.mghpcc.org "
      certs: "certs-mghpcc-2"
    origins:
      - name: origin-2-3
        multus: "mghpcc-2"
        iprange: "2001:48e8:6402:2::3/64"
        gateway: "2001:48e8:6402:2::0"
        ip: "2001:48e8:6402:2::3"
        node: "nrp-sense01.rnd.net2.mghpcc.org "
        certs: "certs-mghpcc-2"
      - name: origin-2-4
        multus: "mghpcc-2"
        iprange: "2001:48e8:6402:2::4/64"
        gateway: "2001:48e8:6402:2::0"
        ip: "2001:48e8:6402:2::4"
        node: "nrp-sense01.rnd.net2.mghpcc.org "
        certs: "certs-mghpcc-2"
      - name: origin-2-5
        multus: "mghpcc-2"
        iprange: "2001:48e8:6402:2::5/64"
        gateway: "2001:48e8:6402:2::0"
        ip: "2001:48e8:6402:2::5"
        node: "nrp-sense01.rnd.net2.mghpcc.org "
        certs: "certs-mghpcc-2"
      - name: origin-2-6
        multus: "mghpcc-2"
        iprange: "2001:48e8:6402:2::6/64"
        gateway: "2001:48e8:6402:2::0"
        ip: "2001:48e8:6402:2::6"
        node: "nrp-sense01.rnd.net2.mghpcc.org "
        certs: "certs-mghpcc-2"